apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
{{ include "nginx.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
    nodePort: {{ .Values.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
